// Generated by gencpp from file beginner_tutorials/AddTwoInts1Request.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ADDTWOINTS1REQUEST_H
#define BEGINNER_TUTORIALS_MESSAGE_ADDTWOINTS1REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct AddTwoInts1Request_
{
  typedef AddTwoInts1Request_<ContainerAllocator> Type;

  AddTwoInts1Request_()
    : duongdi()  {
    }
  AddTwoInts1Request_(const ContainerAllocator& _alloc)
    : duongdi(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _duongdi_type;
  _duongdi_type duongdi;




  typedef boost::shared_ptr< ::beginner_tutorials::AddTwoInts1Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::AddTwoInts1Request_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoInts1Request_

typedef ::beginner_tutorials::AddTwoInts1Request_<std::allocator<void> > AddTwoInts1Request;

typedef boost::shared_ptr< ::beginner_tutorials::AddTwoInts1Request > AddTwoInts1RequestPtr;
typedef boost::shared_ptr< ::beginner_tutorials::AddTwoInts1Request const> AddTwoInts1RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::AddTwoInts1Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::AddTwoInts1Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/ngoc/catkin_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::AddTwoInts1Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::AddTwoInts1Request_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::AddTwoInts1Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::AddTwoInts1Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::AddTwoInts1Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::AddTwoInts1Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::AddTwoInts1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d254ab56be52b378f33caf3ede48462c";
  }

  static const char* value(const ::beginner_tutorials::AddTwoInts1Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd254ab56be52b378ULL;
  static const uint64_t static_value2 = 0xf33caf3ede48462cULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::AddTwoInts1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/AddTwoInts1Request";
  }

  static const char* value(const ::beginner_tutorials::AddTwoInts1Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::AddTwoInts1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] duongdi\n\
";
  }

  static const char* value(const ::beginner_tutorials::AddTwoInts1Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::AddTwoInts1Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.duongdi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoInts1Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::AddTwoInts1Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::AddTwoInts1Request_<ContainerAllocator>& v)
  {
    s << indent << "duongdi[]" << std::endl;
    for (size_t i = 0; i < v.duongdi.size(); ++i)
    {
      s << indent << "  duongdi[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.duongdi[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ADDTWOINTS1REQUEST_H
