// Generated by gencpp from file beginner_tutorials/GoToCertainCell.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_GOTOCERTAINCELL_H
#define BEGINNER_TUTORIALS_MESSAGE_GOTOCERTAINCELL_H

#include <ros/service_traits.h>


#include <beginner_tutorials/GoToCertainCellRequest.h>
#include <beginner_tutorials/GoToCertainCellResponse.h>


namespace beginner_tutorials
{

struct GoToCertainCell
{

typedef GoToCertainCellRequest Request;
typedef GoToCertainCellResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoToCertainCell
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::GoToCertainCell > {
  static const char* value()
  {
    return "aa6b69e8b39989866911686884f64e70";
  }

  static const char* value(const ::beginner_tutorials::GoToCertainCell&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::GoToCertainCell > {
  static const char* value()
  {
    return "beginner_tutorials/GoToCertainCell";
  }

  static const char* value(const ::beginner_tutorials::GoToCertainCell&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::GoToCertainCellRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::GoToCertainCell > 
template<>
struct MD5Sum< ::beginner_tutorials::GoToCertainCellRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::GoToCertainCell >::value();
  }
  static const char* value(const ::beginner_tutorials::GoToCertainCellRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::GoToCertainCellRequest> should match 
// service_traits::DataType< ::beginner_tutorials::GoToCertainCell > 
template<>
struct DataType< ::beginner_tutorials::GoToCertainCellRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::GoToCertainCell >::value();
  }
  static const char* value(const ::beginner_tutorials::GoToCertainCellRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::GoToCertainCellResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::GoToCertainCell > 
template<>
struct MD5Sum< ::beginner_tutorials::GoToCertainCellResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::GoToCertainCell >::value();
  }
  static const char* value(const ::beginner_tutorials::GoToCertainCellResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::GoToCertainCellResponse> should match 
// service_traits::DataType< ::beginner_tutorials::GoToCertainCell > 
template<>
struct DataType< ::beginner_tutorials::GoToCertainCellResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::GoToCertainCell >::value();
  }
  static const char* value(const ::beginner_tutorials::GoToCertainCellResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_GOTOCERTAINCELL_H
